on:
  workflow_dispatch:
  push:
    branches: [main]

env:
  CLOUDFLARE_ACCOUNT_ID: "212aab16e8e2f88974a456b8097b2726"
  CLOUDFLARE_ZONE_ID: "dabase.com"

permissions:
  id-token: write
  contents: read
jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: "stable"
          check-latest: true
      - run: go test ./...
      - uses: aws-actions/setup-sam@v2
        with:
          use-installer: true
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::407461997746:role/github-actions-Role-56IHHM969DKJ
          aws-region: eu-west-2
      - name: Deploy
        run: make deploy